# Generated by Django 6.0.4 on 2026-05-05 03:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_password_hash', models.CharField(blank=True, default='', max_length=255, verbose_name='Senha de Proteção')),
                ('itau_email_encrypted', models.TextField(blank=True, default='', verbose_name='E-mail Itaú Criptografado')),
                ('itau_password_encrypted', models.TextField(blank=True, default='', verbose_name='Senha Itaú Criptografada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fipe_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Código FIPE')),
                ('fipe_initial_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Inicial FIPE')),
                ('fipe_current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Atual FIPE')),
                ('brand', models.CharField(default='Marca não informada', max_length=100, verbose_name='Marca')),
                ('model', models.CharField(default='Modelo não informado', max_length=100, verbose_name='Modelo')),
                ('year', models.IntegerField(default=0, verbose_name='Ano')),
                ('plate', models.CharField(default='SEM-PLACA', max_length=20, verbose_name='Placa')),
                ('color', models.CharField(default='Branco', max_length=50, verbose_name='Cor')),
                ('mileage', models.IntegerField(default=0, verbose_name='Quilometragem')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Compra')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de Venda')),
                ('status', models.CharField(choices=[('estoque', 'Estoque'), ('vendido', 'Vendido'), ('reservado', 'Reservado')], default='estoque', max_length=20, verbose_name='Status')),
                ('publication_sites', models.CharField(blank=True, default='', max_length=255, verbose_name='Sites de Publicação')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Imagem')),
                ('needs_cleaning', models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Precisa Limpar?')),
                ('needs_sanitizing', models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Precisa Higienizar?')),
                ('has_spare_key', models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Tem Chave Reserva?')),
                ('has_cautelar', models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Tem Cautelar?')),
                ('has_procuracao', models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Tem Procuração?')),
                ('has_crlv', models.CharField(choices=[('nao_precisa', 'Não Precisa'), ('nao_tem', 'Não Tem'), ('precisa', 'Precisa')], default='nao_precisa', max_length=20, verbose_name='Tem CRLV?')),
                ('ad_olx', models.BooleanField(default=False, verbose_name='OLX')),
                ('ad_webmotors', models.BooleanField(default=False, verbose_name='WebMotors')),
                ('ad_icarros', models.BooleanField(default=False, verbose_name='iCarros')),
                ('ad_mercado_livre', models.BooleanField(default=False, verbose_name='Mercado Livre')),
                ('ad_facebook', models.BooleanField(default=False, verbose_name='Facebook')),
                ('ad_instagram', models.BooleanField(default=False, verbose_name='Instagram')),
                ('other_ad_sites', models.CharField(blank=True, default='', max_length=255, verbose_name='Outros Sites')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do Contrato')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='cars.car', verbose_name='Carro')),
            ],
        ),
        migrations.CreateModel(
            name='ContractImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contracts/', verbose_name='Imagem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.contract', verbose_name='Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('file_type', models.CharField(choices=[('txt', 'Texto digitado'), ('docx', 'Arquivo DOCX')], max_length=10, verbose_name='Tipo de Arquivo')),
                ('text_content', models.TextField(blank=True, default='', verbose_name='Texto da Nota')),
                ('file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_documents', to='cars.car', verbose_name='Carro')),
            ],
        ),
        migrations.CreateModel(
            name='IPVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('installments', models.IntegerField(choices=[(1, '1x'), (5, '5x')], default=1, verbose_name='Parcelas')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Final')),
                ('installment_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Parcela')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipvas', to='cars.car', verbose_name='Carro')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Venda')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Venda')),
                ('payment_method', models.CharField(blank=True, default='', max_length=100, verbose_name='Forma de Pagamento')),
                ('buyer_type', models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica')], default='fisica', max_length=20, verbose_name='Tipo de Comprador')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, default='', max_length=20, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, default='', max_length=20, verbose_name='RG')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lucro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cars.car', verbose_name='Carro')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('crlv', 'CRLV'), ('dut', 'DUT'), ('nota_fiscal', 'Nota Fiscal'), ('recibo', 'Recibo'), ('contrato', 'Contrato'), ('laudo', 'Laudo'), ('seguro', 'Seguro'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo de Documento')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do Documento')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='cars.car', verbose_name='Carro')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/', verbose_name='Imagem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.vehicledocument', verbose_name='Documento')),
            ],
        ),
    ]
